language: node_js
node_js: '15'
cache: yarn
script: "yarn build && yarn release"
deploy:
  on:
    branch: main
  provider: npm
  email: jfusco311@gmail.com
  api_key: 687900de-bbad-4611-a8b6-a6dc91c89a2a
